### ISSUE TITLE
Test 4

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.GitHub.Bot#4]

**Comment by rodrigok** [comment]
Comment

**Comment by rodrigok** [comment]
Comment 2

**Comment by rodrigok** [comment]
1

**Comment by rodrigok** [comment]
3

**Comment by rodrigok** [comment]
4

**Comment by rodrigok** [comment]
1

**Comment by rodrigok** [comment]
2

**Comment by rodrigok** [comment]
123

**Comment by rodrigok** [comment]
@rocket-cat test

**Comment by rodrigok** [comment]
@rocket-cat test

**Comment by theorenck** [comment]
@rocket-cat close

**Comment by theorenck** [comment]
@rocket-cat label add sokjdakdjalkdsjasldkaj

**Comment by theorenck** [comment]
@rocket-cat label add banana

**Comment by theorenck** [comment]
@rocket-cat label add banana

**Comment by theorenck** [comment]
@rocket-cat label add banana

**Comment by rodrigok** [comment]
@rocket-cat label add banana

**Comment by rodrigok** [comment]
@rocket-cat label add banana

**Comment by rodrigok** [comment]
@rocket-cat label add banana

**Comment by rodrigok** [comment]
@rocket-cat label remove banana

**Comment by theorenck** [comment]
@rocket-cat label remove banana

**Comment by theorenck** [comment]
@rocket-cat label add laranja

**Comment by theorenck** [comment]
@rocket-cat label add "help wanted"

**Comment by theorenck** [comment]
@rocket-cat label remove laranja

**Comment by theorenck** [comment]
@rocket-cat label remove "help wanted"

**Comment by theorenck** [comment]
@rocket-cat close

**Comment by theorenck** [comment]
@rocket-cat open

**Comment by theorenck** [comment]
@TwizzyDizzy can you give it a try and tell me what did you think?

There are only 4 commands and they follow the structure:
@bot-name [command] [operation] [args]

- @bot-name label add [label] *
- @bot-name label remove [label] *
- @bot-name open 
- @bot-name close

*only whitelisted labels for now:
- duplicate
- enhancement
- "help wanted"
- invalid
- question
- wontfix

**Comment by theorenck** [comment]
@theorenck label add abc

**Comment by theorenck** [comment]
@theorenck label add abc

**Comment by theorenck** [comment]
@rocket-cat label add banana

**Comment by theorenck** [comment]
@rocket-cat label add "help wanted"

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment]
@rocket-cat label remove duplicate

**Comment by TwizzyDizzy** [comment]
Hi foobar, I'm closing this issue just because

@rocket-cat close 
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

**Comment by TwizzyDizzy** [comment]
Hi foobar, I'm closing this issue just because

@rocket-cat open

**Comment by TwizzyDizzy** [comment]
@rocket-cat open

Hi foobar, I'm closing this issue just because

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
@rocket-cat add label wontfix

Hi foobar, I'm closing this issue just because

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

**Comment by TwizzyDizzy** [comment]
@rocket-cat open

**Comment by TwizzyDizzy** [comment]
@rocket-cat label remove duplicate

**Comment by TwizzyDizzy** [comment]
Hi @theorenck 

* I tested open/close/reopen: **works**.
* I have tested adding / removing labels: **works** (I haven't tested with every whitelisted label, yet I assume that if it works with one, it also works with all other whitelisted labels)

Some remarks though:

* `rocket-cat` only seems to be triggered, if the action to be taken is contained in the first line of the comment. This should either be fixed or put into documentation later. It's not really a showstopper, yet I rather like to first justify my action, then actually trigger it. But as I said, not really important.

* It's not possible to trigger multiple actions. For example, if I wanted to close and label an issue in the same comment, that would currently not be possible (I'm thinking here of usual combinations like **close** + **add label duplicate**)

* on deleting a comment that contains an action, `rocket-cat` fires another time and does that action again. this is usually no problem, but I wanted to bring it to your attention.

* **Question:** is it possible to attach a text to specific labels from the `rocket-cat` side. For example: if I add a label "invalid" it might be very nice to have a standard text for this action like: "closing this because you didn't follow the issue template. here is a link to whatever documentation". This would save a lot of effort and would streamline comments/reactions to usual problems (like missing issue template). Ha! **EDIT**: it seems like, in general, something like that is possible with `probot`: https://github.com/probot/probot/blob/master/.github/config.yml

Cheers so far & thanks for your efforts!
Thomas

**Comment by theorenck** [comment]
Thanks for your the feedback @TwizzyDizzy

About the your remarks:

> rocket-cat only seems to be triggered, if the action to be taken is contained in the first line of the comment. This should either be fixed or put into documentation later. It's not really a showstopper, yet I rather like to first justify my action, then actually trigger it. But as I said, not really important.

For the sake of simplicity, yes. But we can improve that later sure. Can you open an issue for that?

> It's not possible to trigger multiple actions. For example, if I wanted to close and label an issue in the same comment, that would currently not be possible (I'm thinking here of usual combinations like close + add label duplicate)

Yes, this one would be in our roadmap. 

> on deleting a comment that contains an action, rocket-cat fires another time and does that action again. this is usually no problem, but I wanted to bring it to your attention.

A bug nonetheless, will be fixed as soon as possible.

> Question: is it possible to attach a text to specific labels from the rocket-cat side. For example: if I add a label "invalid" it might be very nice to have a standard text for this action like: "closing this because you didn't follow the issue template. here is a link to whatever documentation". This would save a lot of effort and would streamline comments/reactions to usual problems (like missing issue template). Ha! EDIT: it seems like, in general, something like that is possible with probot: https://github.com/probot/probot/blob/master/.github/config.yml

An outstanding idea, can you please create a issue for that.

Best regards and thanks for your time and patience.
Theo

**Comment by TwizzyDizzy** [comment]
Hi Theo,

New issue for triggering not only on mentions in only the first line of a comment: https://github.com/RocketChat/Rocket.Chat.GitHub.Bot/issues/6

New issue for standardized actions: https://github.com/RocketChat/Rocket.Chat.GitHub.Bot/issues/7

Cheers
Thomas

**Comment by theorenck** [comment]
@rocket-cat label add wontfix

**Comment by theorenck** [comment]
@rocket-cat label remove wontfix

**Comment by theorenck** [comment]
@rocket-cat label add wontfix

**Comment by theorenck** [comment]
@rocket-cat label remove wontfix

**Comment by theorenck** [comment]
Hi @TwizzyDizzy 

> on deleting a comment that contains an action, rocket-cat fires another time and does that action again. this is usually no problem, but I wanted to bring it to your attention.

I believe that the problem was solved. Let me know if I am wrong.

Cheers,

**Comment by TwizzyDizzy** [comment]
@rocket-cat open

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

**Comment by TwizzyDizzy** [comment]
@theorenck 

>> on deleting a comment that contains an action, rocket-cat fires another time and does that action again. this is usually no problem, but I wanted to bring it to your attention.

> I believe that the problem was solved. Let me know if I am wrong.

Tested and verified. Doesn't fire anymore on deleting a comment.

Cheers
Thomas
